[workspace]
channels = ["knime/label/nightly", "knime", "conda-forge"] # TODO remove the knime/label/nightly channel when 5.5 is released
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
knime-extension = "*"
knime-python-base = "*"

[feature.build.dependencies]
python = "3.9.*"
knime-extension-bundling = { version = "5.5.*", build="202506271444" } # TODO remove the build version when 5.5 is released

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "python ./.pixi/envs/build/bin/build_python_extension.py . {{ dest }}"}

[environments]
build = {features = ["build"], no-default-feature = true}

