name: Secrets Detection
run-name: Scanning for exposed secrets and credentials

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:
  schedule:
    # Run daily at 3 AM UTC
    - cron: '0 3 * * *'

jobs:

  gitleaks:
    name: Gitleaks Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # needed for organizational repos, get one here: https://gitleaks.io/
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}


  secrets-summary:
    name: Secrets Detection Summary
    runs-on: ubuntu-latest
    needs: [gitleaks]
    if: always()
    steps:
      - name: Create secrets summary
        run: |
          echo "## 🔍 Secrets Detection Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Tool | Status | Description |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|-------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Gitleaks | ${{ needs.gitleaks.result }} | Detect and prevent secrets in git repos |" >> $GITHUB_STEP_SUMMARY
